version: "3"

services:
    portfolio-frontend-proxy:
        container_name: portfolio-frontend-proxy
        build:
            context: ../../
            dockerfile: ./tools/docker/dockerfile.build
        image: portfolio-frontend-proxy
        ports:
            - "80:80"
            - "443:443"
        restart: always
    portfolio-frontend:
        container_name: portfolio-frontend
        build:
            context: ../../
            dockerfile: ./tools/docker/dockerfile.next
        image: portfolio-frontend
        env:
            - AUTH_TRUST_HOST=true
        ports:
            - "3000:3000"
        restart: always
