version: "3"

services:
    proxy:
        container_name: portfolio-proxy
        build:
            context: ../../
            dockerfile: ./tools/docker/dockerfile.local
        image: portfolio-proxy
        ports:
            - "80:80"
            - "443:443"
        restart: always
    portfolio-fe-local:
        container_name: portfolio-fe-local
        build:
            context: ../../
            dockerfile: ./tools/docker/dockerfile.next
        image: portfolio-fe-local
        env:
            - AUTH_TRUST_HOST=true
        ports:
            - "3000:3000"
        restart: always
