version: "3"
services:
    portfolio-frontend-proxy:
        image: registry.digitalocean.com/${DOCKER_REGISTRY}/portfolio-frontend-proxy:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
    portfolio-frontend:
        image: registry.digitalocean.com/${DOCKER_REGISTRY}/portfolio-frontend:latest
        environment:
            - AUTH_TRUST_HOST=true
        ports:
            - "3000:3000"
        restart: always
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
    portfolio-backend:
        image: registry.digitalocean.com/${DOCKER_REGISTRY}/portfolio-backend:latest
        ports:
            - 8000:8000
        restart: always
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
